name: json_serializable_ext
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  json_serializable: ">=3.3.0 <4.0.0"
  json_annotation: ">=3.0.0 <4.0.0"
  built_collection: ">=4.0.0 <5.0.0"
  build_runner: ">=1.9.0 <2.0.0"
  source_gen: ">=0.9.5 <=1.0.0"
  analyzer: ">=0.39.8 <1.0.0"
  build: ">=1.0.0 <2.0.0"
